import { Ionicons } from '@expo/vector-icons';
import { router } from 'expo-router';
import { StatusBar } from 'expo-status-bar';
import React from 'react';
import { Image, Linking, Pressable, StyleSheet, View } from 'react-native';
import Animated, { FadeIn } from 'react-native-reanimated';
import { SafeAreaView } from 'react-native-safe-area-context';

import { Typography } from '@/shared/components';
import { useStatusBarStyle } from '@/shared/hooks/useStatusBarStyle';
import { fonts, palette, useTheme } from '@/shared/theme';

const LOGO = require('../../../../assets/images/logo.png');
const SUPPORT_EMAIL = 'privacy@fitcall.me';

export function PrivacyPolicyScreen() {
  const { colors } = useTheme();
  const statusBarStyle = useStatusBarStyle();

  const handleBack = () => {
    if (router.canGoBack()) router.back();
  };

  const openEmail = () => Linking.openURL(`mailto:${SUPPORT_EMAIL}`);

  return (
    <SafeAreaView
      edges={['top', 'bottom']}
      style={[styles.safe, { backgroundColor: colors.background }]}
    >
      <StatusBar style={statusBarStyle} />

      <View style={styles.headerBar}>
        <Pressable hitSlop={12} onPress={handleBack} style={styles.backBtn}>
          <Ionicons name="arrow-back" size={22} color={colors.text} />
        </Pressable>
      </View>

      <Animated.ScrollView
        entering={FadeIn.duration(280)}
        contentContainerStyle={styles.scrollContent}
        showsVerticalScrollIndicator={false}
      >
        <View style={styles.brandRow}>
          <Image source={LOGO} style={styles.brandLogo} resizeMode="contain" />
          <Typography style={[styles.brandText, { color: colors.text }]}>FITCALL</Typography>
        </View>

        <Typography style={[styles.pageTitle, { color: colors.text }]}>Privacy Policy</Typography>
        <Typography style={[styles.lastUpdated, { color: colors.textSecondary }]}>
          Last Updated: May 2, 2026
        </Typography>

        <Body>
          Welcome to FitCall.Me. Your privacy is a fundamental priority for us. This Privacy Policy
          explains how we collect, use, disclose, and safeguard your information when you use our
          mobile application and website (collectively, the &quot;Service&quot;).
        </Body>

        <Section number="1" title="Information We Collect">
          <Body>
            We collect information that you provide directly to us, data generated by your use of
            the Service, and information from third-party sources.
          </Body>

          <Subsection letter="A" title="Personal Identification Information">
            <Bullet
              bold="Account Data:"
              text="Name, email address, date of birth, gender, and profile picture."
            />
            <Bullet
              bold="Authentication:"
              text="Login credentials and third-party social media tokens (e.g., Google or Apple ID)."
            />
          </Subsection>

          <Subsection letter="B" title="Health and Fitness Data (Sensitive Information)">
            <Body>
              Because FitCall.Me is a fitness app, we process data that may be considered sensitive:
            </Body>
            <Bullet
              bold="Biometric Data:"
              text="Height, weight, body fat percentage, and heart rate."
            />
            <Bullet
              bold="Activity Data:"
              text="Step counts, calories burned, exercise types, duration, and intensity."
            />
            <Bullet
              bold="Sync Data:"
              text="Information imported from health kits (Apple Health, Google Fit) or wearable devices."
            />
          </Subsection>

          <Subsection letter="C" title="Technical and Usage Data">
            <Bullet
              bold="Geolocation:"
              text="Precise location data (GPS) to track runs, walks, or cycling routes (only with your explicit consent)."
            />
            <Bullet
              bold="Device Info:"
              text="IP address, device ID, operating system, and app version."
            />
            <Bullet bold="Log Data:" text="Time of access, pages viewed, and system crashes." />
          </Subsection>
        </Section>

        <Section number="2" title="How We Use Your Information">
          <Body>We process your data to provide a personalized fitness experience:</Body>
          <Bullet
            bold="Core Functionality:"
            text="To calculate caloric burn, track progress against goals, and provide workout recommendations."
          />
          <Bullet
            bold="Communication:"
            text={
              'To send system updates, security alerts, and motivational "FitCalls" or reminders.'
            }
          />
          <Bullet
            bold="Personalization:"
            text="To tailor training programs based on your fitness level and physical metrics."
          />
          <Bullet
            bold="Safety & Security:"
            text="To prevent fraud, protect our users, and comply with legal obligations."
          />
        </Section>

        <Section number="3" title="Data Sharing and Disclosure">
          <Body>
            We do not sell your personal or health data to third parties. We only share information
            in the following circumstances:
          </Body>
          <Bullet
            bold="Service Providers:"
            text="With vendors who perform cloud hosting, data analysis, or payment processing."
          />
          <Bullet
            bold="Legal Necessity:"
            text="If required by law, subpoena, or to protect the safety of any person."
          />
          <Bullet
            bold="Business Transfers:"
            text="In connection with a merger, sale of assets, or acquisition."
          />
          <Bullet
            bold="With Your Consent:"
            text="If you choose to share your progress on social media or join a public leaderboard within the app."
          />
        </Section>

        <Section number="4" title="Data Retention">
          <Body>We retain your personal information for as long as your account is active.</Body>
          <Bullet text="If you request account deletion, we will purge your personal data from our active databases within 30 days." />
          <Bullet text="We may retain de-identified, aggregated data for research and product improvement purposes indefinitely." />
        </Section>

        <Section number="5" title="Your Rights and Choices">
          <Body>Depending on your location, you may have the following rights:</Body>
          <Bullet
            bold="Access & Portability:"
            text="Request a copy of the data we hold about you."
          />
          <Bullet bold="Correction:" text="Update inaccurate or incomplete information." />
          <Bullet
            bold="Deletion:"
            text={'Request that we erase your personal data ("The Right to be Forgotten").'}
          />
          <Bullet
            bold="Withdraw Consent:"
            text="Revoke permissions for GPS tracking or Health Kit syncing at any time via your device settings."
          />
        </Section>

        <Section number="6" title="Security Measures">
          <Body>We implement industry-standard security protocols, including:</Body>
          <Bullet
            bold="Encryption:"
            text="Data is encrypted both in transit (TLS) and at rest (AES-256)."
          />
          <Bullet
            bold="Access Control:"
            text="Access to sensitive health data is restricted to authorized personnel only."
          />
          <Bullet
            bold="Anonymization:"
            text="Where possible, we use pseudonymized data for internal analytics."
          />
        </Section>

        <Section number="7" title="Children's Privacy">
          <Body>
            FitCall.Me is not intended for use by children under the age of 13 (or 16 in certain
            jurisdictions). We do not knowingly collect data from children. If we become aware of
            such data collection, we will take immediate steps to delete it.
          </Body>
        </Section>

        <Section number="8" title="Changes to This Policy">
          <Body>
            We may update this Privacy Policy periodically. We will notify you of significant
            changes by posting a notice within the app or sending an email to your registered
            address.
          </Body>
        </Section>

        <Section number="9" title="Contact Us">
          <Body>
            If you have questions or concerns regarding this policy, please contact our Data
            Protection Officer at:
          </Body>
          <View style={styles.emailRow}>
            <Typography style={[styles.bodyBold, { color: colors.text }]}>Email: </Typography>
            <Pressable onPress={openEmail} hitSlop={4}>
              <Typography style={styles.emailLink}>{SUPPORT_EMAIL}</Typography>
            </Pressable>
          </View>
        </Section>
      </Animated.ScrollView>
    </SafeAreaView>
  );
}

function Body({ children }: { children: React.ReactNode }) {
  const { colors } = useTheme();
  return <Typography style={[styles.body, { color: colors.textSecondary }]}>{children}</Typography>;
}

interface SectionProps {
  number: string;
  title: string;
  children: React.ReactNode;
}

function Section({ number, title, children }: SectionProps) {
  const { colors } = useTheme();
  return (
    <View style={styles.section}>
      <Typography style={[styles.sectionTitle, { color: colors.text }]}>
        {number}. {title}
      </Typography>
      {children}
    </View>
  );
}

interface SubsectionProps {
  letter: string;
  title: string;
  children: React.ReactNode;
}

function Subsection({ letter, title, children }: SubsectionProps) {
  const { colors } = useTheme();
  return (
    <View style={styles.subsection}>
      <Typography style={[styles.subsectionTitle, { color: colors.text }]}>
        {letter}. {title}
      </Typography>
      {children}
    </View>
  );
}

interface BulletProps {
  bold?: string;
  text: string;
}

function Bullet({ bold, text }: BulletProps) {
  const { colors } = useTheme();
  return (
    <View style={styles.bulletRow}>
      <Typography style={[styles.bulletDot, { color: colors.textSecondary }]}>•</Typography>
      <Typography style={[styles.bulletText, { color: colors.textSecondary }]}>
        {bold ? (
          <Typography style={[styles.bulletBold, { color: colors.text }]}>{bold} </Typography>
        ) : null}
        {text}
      </Typography>
    </View>
  );
}

const styles = StyleSheet.create({
  safe: {
    flex: 1,
  },
  headerBar: {
    paddingHorizontal: 20,
    paddingTop: 4,
    paddingBottom: 4,
  },
  backBtn: {
    width: 24,
    height: 24,
    alignItems: 'center',
    justifyContent: 'center',
  },
  scrollContent: {
    paddingHorizontal: 22,
    paddingBottom: 40,
  },
  brandRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    marginTop: 4,
    marginBottom: 18,
  },
  brandLogo: {
    width: 22,
    height: 22,
  },
  brandText: {
    fontSize: 18,
    fontFamily: fonts.bold,
    letterSpacing: 0.5,
  },
  pageTitle: {
    fontSize: 22,
    fontFamily: fonts.bold,
    textAlign: 'center',
  },
  lastUpdated: {
    fontSize: 11,
    fontFamily: fonts.regular,
    textAlign: 'center',
    marginTop: 4,
    marginBottom: 18,
  },
  body: {
    fontSize: 12,
    fontFamily: fonts.regular,
    lineHeight: 18,
    marginTop: 6,
    textAlign: 'justify',
  },
  bodyBold: {
    fontSize: 12,
    fontFamily: fonts.semibold,
    lineHeight: 18,
  },
  section: {
    marginTop: 18,
    gap: 4,
  },
  sectionTitle: {
    fontSize: 13,
    fontFamily: fonts.bold,
    marginBottom: 2,
  },
  subsection: {
    marginTop: 12,
    gap: 2,
  },
  subsectionTitle: {
    fontSize: 12,
    fontFamily: fonts.semibold,
    marginBottom: 2,
  },
  bulletRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    marginTop: 6,
    gap: 6,
    paddingLeft: 6,
  },
  bulletDot: {
    fontSize: 12,
    lineHeight: 18,
  },
  bulletText: {
    flex: 1,
    fontSize: 12,
    fontFamily: fonts.regular,
    lineHeight: 18,
    textAlign: 'justify',
  },
  bulletBold: {
    fontSize: 12,
    fontFamily: fonts.semibold,
    lineHeight: 18,
  },
  emailRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 6,
  },
  emailLink: {
    fontSize: 12,
    fontFamily: fonts.regular,
    color: palette.highlightBlue['5'],
    textDecorationLine: 'underline',
  },
});
